version: "2.4"
services:
  app: &service_app
    build: .
    image: freshshell/fresh-api
    restart: unless-stopped
    logging: &logging
      driver: syslog
      options:
        tag: '{{.Name}}/{{.ID}}'
    depends_on:
      cache:
        condition: service_healthy
    deploy:
      replicas: 0
    environment:
      RACK_ENV: production
      MEMCACHE_SERVERS: cache:11211
  web:
    <<: *service_app
    deploy:
      replicas: 1
    command: "rackup -p 80 -O Verbose"
    expose:
      - 80
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/80'"]
      interval: 10s
      timeout: 5s
  cache:
    image: memcached:1
    restart: unless-stopped
    command: memcached -m 32
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/11211'"]
      interval: 10s
      timeout: 5s
    logging:
      <<: *logging
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-fresh-api
